---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

# - name: "Bash | Detect oh-my-posh"
#   ansible.builtin.stat:
#     path: "{{ ansible_user_dir }}/.oh-my-posh"
#   register: ohmyposh

# - name: "Bash | Register oh-my-posh state"
#   ansible.builtin.set_fact:
#     ohmyposh_is_installed: "{{ ohmyposh.stat.exists }}"

# - name: "Bash | Debug ohmyposh_is_installed"
#   ansible.builtin.debug:
#     var: ohmyposh_is_installed

# - name: "Bash | Install oh-my-posh"
#   when: not ohmyposh_is_installed
#   block:
#     - name: "Bash | Download oh-my-posh Install Script"
#       ansible.builtin.get_url:
#         url: https://ohmyposh.dev/install.sh
#         dest: /{{ ansible_user_dir }}/oh-my-posh.install.sh
#         force: true
#         mode: "0755"
#       notify:
#         - "Bash | Cleanup oh-my-posh install script"

#     - name: "Bash | Run the install script"
#       ansible.builtin.script:
#         cmd: /{{ ansible_user_dir }}/oh-my-posh.install.sh

- name: "Bash | Copy .bashrc"
  ansible.builtin.copy:
    src: ".bashrc"
    dest: "{{ ansible_user_dir }}/.bashrc"
    mode: "0644"

- name: "Bash | Copy .profile"
  ansible.builtin.copy:
    src: ".profile"
    dest: "{{ ansible_user_dir }}/.profile"
    mode: "0644"

- name: "Bash | Copy custom bash config"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/"
    src: "bash"
    mode: "0644"
    directory_mode: "0755"
    force: true

- name: "Bash | Copy custom bash theme"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/oh-my-posh"
    src: "themes"
    directory_mode: "0755"
    mode: "0644"
    force: true

- name: "Bash | {{ ansible_distribution }} | Identify distribution config"
  ansible.builtin.stat:
    path: "{{ role_path }}/files/os/{{ ansible_distribution }}"
  register: bash_os_distribution_config

- name: "Bash | {{ ansible_os_family }} | Identify os family config"
  ansible.builtin.stat:
    path: "{{ role_path }}/files/os/{{ ansible_os_family }}"
  register: bash_os_family_config
  when: not bash_os_distribution_config.stat.exists

- name: "Bash | Calculate os config src"
  ansible.builtin.set_fact:
    bash_os_config: "{{ bash_os_distribution_config if bash_os_distribution_config.stat.exists else bash_os_family_config }}"

- name: "Bash | Copy custom bash config for os: {{ bash_os_config.stat.path | basename }}"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/bash/"
    src: "{{ bash_os_config.stat.path }}/"
    mode: "0644"
    force: true
  when:
    - bash_os_config is defined
    - bash_os_config.stat.exists
