---
- name: "Zsh | Ubuntu | Install"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - zsh
    - oh-my-posh

- name: "Zsh | Set default terminal"
  ansible.builtin.user:
    name: "{{ host_user }}"
    shell: /usr/bin/zsh
  become: true
