"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$time\
$directory\
$git_branch$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$cmd_duration\
$status\
\n$character"""

[username]
style_user = "bold #242424 bg:#f1184c"
style_root = "bold #242424 bg:#f1184c"
format = "[$user]($style)"
disabled = false
show_always = true

[os]
format = "[ $symbol ]($style)"
style = "fg:#3A86FF bg:#282c34"
disabled = false

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[time]
disabled = false
format = '[ $time ]($style)'
time_format = "%T"
style = "fg:#FFBB00 bg:#242424"

[directory]
style = "fg:#33DD2D bg:#242424"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
symbol = ""
style = "bg:#242424"
format = '[[ $symbol $branch ](fg:#3A86FF bg:#242424)]($style)'

[git_status]
style = "bg:#242424"
format = '[[($all_status$ahead_behind )](fg:#3A86FF bg:#242424)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[php]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[conda]
symbol = "  "
style = "fg:crust bg:sapphire"
format = '[$symbol$environment ]($style)'
ignore_base = false

[cmd_duration]
min_time = 1_000
format = "[  $duration ]($style)"  # U+EBA2 stopwatch
style = "fg:#ffffff bg:#8800dd"

[status]
format = '[  ]($style)'  # U+EB05 status icon
style = "fg:#242424 bg:#33DD2D"
disabled = false

[character]
success_symbol = "[➜](bold #f1184c)"
error_symbol = "[➜](bold #f1184c)"
