---
- name: Detect Bitwarden
  ansible.builtin.command:
    cmd: which bw
  changed_when: false
  failed_when: false
  register: bw_installed

- name: Register Bitwarden
  ansible.builtin.set_fact:
    bw_installed: "{{ bw_installed.rc == 0 }}"
  when: bw_installed.rc == 0
