---
# - name: "Bitwarden | Install Bitwarden"
#   ansible.builtin.apt:
#     name: bitwarden-cli
#     state: present
#     update_cache: true
#   become: true

# - name: "Bash | Ubuntu | Install"
#   ansible.builtin.package:
#     name: "{{ item }}"
#     state: present
#   loop:
#     - bash

- name: Download Bitwarden CLI zip file
  ansible.builtin.get_url:
    url: "https://vault.bitwarden.com/download/?app=cli&platform=linux"
    dest: "/tmp/bw.zip"
    mode: "0644"
- name: Unarchive Bitwarden CLI
  ansible.builtin.unarchive:
    src: "/tmp/bw.zip"
    dest: "/tmp"

- name: Move Bitwarden CLI to /usr/local/bin
  copy:
    src: "/tmp/bw"
    dest: "/usr/local/bin/bw"
    mode: "0755"
  become: true

- name: Verify Bitwarden CLI is installed
  command: "/usr/local/bin/bw --version"
  register: bw_version_output

- name: Show Bitwarden CLI version
  debug:
    msg: "Bitwarden CLI installed: {{ bw_version_output.stdout }}"
